# gui/log_viewer.py
# This module provides a log viewer window for the TAILSCALE VPN Client using CustomTkinter. It allows users to view, search, and clear log files generated by the application. 

import customtkinter as ctk
from tkinter import messagebox
import os
from logic.logger import get_global_log_dir

class LogViewer(ctk.CTkToplevel):
    def __init__(self, parent, filename, display_title):
        super().__init__(parent)
        self.title(f"Log: {display_title}")
        self.geometry("800x700")
        
        # --- FOCUS FIXES ---
        self.lift()                          # Move to top of stack
        self.focus_force()                   # Take keyboard focus
        self.after(10, self.lift)            # Double-check lift after init
        
        # Point to our new GlobalLogs folder
        self.log_file = os.path.join(get_global_log_dir(), filename)
        self.last_search_index = "1.0"

        # --- TOP TOOLBAR ---
        self.toolbar = ctk.CTkFrame(self, height=70, corner_radius=0)
        self.toolbar.pack(side="top", fill="x")

        self.lbl_title = ctk.CTkLabel(self.toolbar, text=display_title, font=ctk.CTkFont(size=18, weight="bold"))
        self.lbl_title.pack(side="left", padx=20)

        # Search Bar
        self.search_entry = ctk.CTkEntry(self.toolbar, placeholder_text="Search logs...", width=200)
        self.search_entry.pack(side="left", padx=10)
        self.search_entry.bind("<Return>", lambda e: self._search_text())

        self.btn_search = ctk.CTkButton(self.toolbar, text="🔍 Find Next", width=80, command=self._search_text, fg_color="gray")
        self.btn_search.pack(side="left", padx=5)

        # Action Buttons
        self.btn_refresh = ctk.CTkButton(self.toolbar, text="🔄 Refresh", width=90, command=self._read_content)
        self.btn_refresh.pack(side="right", padx=10)

        self.btn_clear = ctk.CTkButton(self.toolbar, text="🗑 Clear", width=90, command=self._clear_log, fg_color="#F44336", hover_color="#D32F2F")
        self.btn_clear.pack(side="right", padx=5)

        # --- CONTENT AREA ---
        self.text_widget = ctk.CTkTextbox(self, font=("Consolas", 12), activate_scrollbars=True, wrap="none")
        self.text_widget.pack(fill="both", expand=True, padx=15, pady=15)
        
        # Formatting Tags
        self.text_widget.tag_config("INFO", foreground="#4CAF50")
        self.text_widget.tag_config("WARNING", foreground="#FFC107")
        self.text_widget.tag_config("ERROR", foreground="#F44336")
        self.text_widget.tag_config("HIGHLIGHT", background="#444444", foreground="#FFFFFF")

        self._read_content()

    def _search_text(self):
        """Finds and highlights matches."""
        query = self.search_entry.get()
        if not query: return

        # Search from last position
        start_pos = self.text_widget.search(query, self.last_search_index, stopindex="end", nocase=True)
        
        if not start_pos:
            # Wrap around to top
            start_pos = self.text_widget.search(query, "1.0", stopindex="end", nocase=True)
            if not start_pos:
                return # No matches found

        end_pos = f"{start_pos}+{len(query)}c"
        self.text_widget.tag_remove("HIGHLIGHT", "1.0", "end")
        self.text_widget.tag_add("HIGHLIGHT", start_pos, end_pos)
        self.text_widget.see(start_pos)
        self.last_search_index = end_pos

    def _read_content(self):
        """Loads log content with color tags."""
        if not os.path.exists(self.log_file):
            self._update_display(f"[Log file not found or logging is disabled: {self.log_file}]")
            return

        self.text_widget.configure(state="normal")
        self.text_widget.delete("1.0", "end")
        
        try:
            with open(self.log_file, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    tag = None
                    up = line.upper()
                    if "ERROR" in up: tag = "ERROR"
                    elif "WARNING" in up: tag = "WARNING"
                    elif "INFO" in up: tag = "INFO"
                    self.text_widget.insert("end", line, tag)
        except Exception as e:
            self.text_widget.insert("end", f"Failed to read: {e}")
        
        self.text_widget.configure(state="disabled")
        self.text_widget.see("end") # Auto-scroll to latest entry

    def _update_display(self, text):
        self.text_widget.configure(state="normal")
        self.text_widget.delete("1.0", "end")
        self.text_widget.insert("1.0", text)
        self.text_widget.configure(state="disabled")

    def _clear_log(self):
        if messagebox.askyesno("Confirm", "Clear this log file?"):
            try:
                open(self.log_file, "w").close()
                self._read_content()
            except Exception as e:
                messagebox.showerror("Error", str(e))